[options]
admin_passwd = $pbkdf2-sha512$600000$Vuq9l1Iq5ZxzznkvxVir9Q$/JYvO80NJ6RwVkqahZeRruFQj1pllWcq9hHBsMwTPDr2eOnsG.1dHKjiFp0llNMeYF2l4q9S9Cgd28Zho6HunQ
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
update = acceso_ies,web

